os:
- linux
- osx
#- windows
language: rust
rust:
- stable
cache: cargo
before_deploy:
  - bash ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: iAANKduP2lubHQ4v/CzdoMGVscvj/gmNrKnFtDLAQJy0xGddKV8zz7DDzPIxA+noZgRQygkjVKMbnjykITi4FDBox7mahFlz6vBf8W+j+JR9nh477TiGKd+AGLvqCAgL4kcsCyWqoSm8fnJx9QRz0tzDqwh1n5X9zk5B9oaORa5/Lh2oZ6G5+sdQDiS0zBrlGzAi3k94SZq76HBkE4gEgYu/tNre6HwLtafVRT5QG6EFlgioxgSOn4YlURyerDb+WKgp2WoAMbNG9j01HhkmzDXhxOl56g9Ta++VC5LgIOmV3MFV33vu9gSaT9r0ktgI4dqqcntJsFT/27H9pW2d7lC5a14L4uUYp6EPayWfPtgVU0v5B5YHHvdS5pJwwUK70O/iSmyBsNSfqe1RSaNYeQooICJmtU0yimN533liQy90P01RZbZPoKoxYO30m6CqZMPUYxhuS/VwXu+tAaYeKw3J21/Dd8dTBvNF9EaokWamIFoLdTHdXGaxMZOsntBAQbRebQVrZpAFBLlss4VLuxAD9Ywrtq4z+INztWgGuG4Fn9NX0ObECoAFJrNcC9n3GFx7Do9SxOYaW+cIbx6oGy8X28pR7KVPVjaRDnOlVyOTNbeWMEuPgZDxjhIAk5ggLglr/ML2TyySYYEDvw5nrGeFD6Zt0SM9RQ5Pys8nW+0=
  skip_cleanup: true
  on:
    repo: nikita2206/envpopulate
  file_glob: true
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*

#jobs:
#  include:
#  - stage: GitHub Release
#    deploy:
#      provider: releases
#      api_key:
#        secure: iAANKduP2lubHQ4v/CzdoMGVscvj/gmNrKnFtDLAQJy0xGddKV8zz7DDzPIxA+noZgRQygkjVKMbnjykITi4FDBox7mahFlz6vBf8W+j+JR9nh477TiGKd+AGLvqCAgL4kcsCyWqoSm8fnJx9QRz0tzDqwh1n5X9zk5B9oaORa5/Lh2oZ6G5+sdQDiS0zBrlGzAi3k94SZq76HBkE4gEgYu/tNre6HwLtafVRT5QG6EFlgioxgSOn4YlURyerDb+WKgp2WoAMbNG9j01HhkmzDXhxOl56g9Ta++VC5LgIOmV3MFV33vu9gSaT9r0ktgI4dqqcntJsFT/27H9pW2d7lC5a14L4uUYp6EPayWfPtgVU0v5B5YHHvdS5pJwwUK70O/iSmyBsNSfqe1RSaNYeQooICJmtU0yimN533liQy90P01RZbZPoKoxYO30m6CqZMPUYxhuS/VwXu+tAaYeKw3J21/Dd8dTBvNF9EaokWamIFoLdTHdXGaxMZOsntBAQbRebQVrZpAFBLlss4VLuxAD9Ywrtq4z+INztWgGuG4Fn9NX0ObECoAFJrNcC9n3GFx7Do9SxOYaW+cIbx6oGy8X28pR7KVPVjaRDnOlVyOTNbeWMEuPgZDxjhIAk5ggLglr/ML2TyySYYEDvw5nrGeFD6Zt0SM9RQ5Pys8nW+0=
#      skip_cleanup: true
#      on:
#        repo: nikita2206/envpopulate
#      file_glob: true
#      file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*
